name: Snyk IaC Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  snyk-iac:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk CLI
        uses: snyk/actions/setup@master

      - name: Run Snyk IaC scan & generate SARIF
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          snyk iac test --file=. --sarif --severity-threshold=high > snyk-iac.sarif

      - name: Upload SARIF to GitHub Code Scanning
        if: always()  # Run even on scan errors
        uses: github/codeql-action/upload-sarif@v3 # Dodges deprecation
        with:
          sarif_file: snyk-iac.sarif
